# Generated by Django 5.1.7 on 2025-03-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('accountnum', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('principle', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
